name: czech
description: "Set of Czechia-specific functions: parse and validate bank account number, personal ID, company ID, ... Hezky Äesky!"
version: 3.0.2
homepage: https://github.com/fnx-io/czech

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mod97: ^1.0.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
